# Generated by Django 6.0.4 on 2026-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_course_description_alter_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('RN', 'Active'), ('CM', 'Completed'), ('DR', 'Dropped')], default='RN', max_length=2),
        ),
    ]
