# Generated by Django 6.0.4 on 2026-05-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('CM', 'Completed'), ('DR', 'Dropped')], default='AC', max_length=2),
        ),
    ]
