# Generated by Django 6.0.4 on 2026-05-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='marks_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
