# Generated by Django 6.0.4 on 2026-05-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_submission_marks_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('AC', 'Active'), ('FN', 'Finished')], default='PN', max_length=2),
        ),
    ]
