# Generated by Django 6.0.4 on 2026-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_sponsorship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('IN', 'Informative'), ('AL', 'Alert'), ('WR', 'Warning')], default='IN', max_length=2),
        ),
    ]
