# Generated by Django 6.0.4 on 2026-05-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
    ]
