# Generated by Django 6.0.4 on 2026-05-11 00:38

import django.db.models.deletion
from django.db import migrations, models


def move_submission_grades_to_evaluation(apps, schema_editor):
    Submission = apps.get_model('lms', 'Submission')
    Evaluation = apps.get_model('lms', 'Evaluation')

    evaluations = []
    for submission in Submission.objects.all():
        evaluations.append(
            Evaluation(
                submission_id=submission.id,
                marks_obtained=submission.marks_obtained,
                status=submission.status,
            )
        )

    Evaluation.objects.bulk_create(evaluations)


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_remove_course_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('AP', 'Approved'), ('RJ', 'Rejected')], default='PN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='lms.submission')),
            ],
        ),
        migrations.RunPython(move_submission_grades_to_evaluation, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='submission',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
    ]
