# Generated by Django 6.0.4 on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_required_course_fields(apps, schema_editor):
    Course = apps.get_model('lms', 'Course')
    User = apps.get_model('users', 'User')

    Course.objects.filter(description__isnull=True).update(description='')
    Course.objects.filter(price__isnull=True).update(price=0)

    instructor = User.objects.filter(role='IN').first()
    if instructor is None and Course.objects.filter(instructor__isnull=True).exists():
        raise ValueError("Create at least one instructor user before applying this migration.")

    if instructor:
        Course.objects.filter(instructor__isnull=True).update(instructor=instructor)


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_alter_course_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fill_required_course_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'IN'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
